# 서버 설정
server.port=9091

# logging 설정
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO

# encoding 설정
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

# MyBatis 설정
mybatis.configuration.map-underscore-to-camel-case=true